// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package crawler

import (
	"sync-ethereum/internal/config"
	"sync-ethereum/internal/delivery/crawler"
	"sync-ethereum/internal/service/ethclient_crawler"
	"sync-ethereum/internal/wireset"
)

// Injectors from wire.go:

func Initialize(configPath string) (Application, error) {
	configConfig, err := config.NewConfig(configPath)
	if err != nil {
		return Application{}, err
	}
	logger, err := wireset.InitLogger(configConfig)
	if err != nil {
		return Application{}, err
	}
	mq, err := wireset.InitMQ(configConfig, logger)
	if err != nil {
		return Application{}, err
	}
	crawlerService := ethclient_crawler.NewEthClientCrawlerService(configConfig)
	crawlerCrawler := crawler.NewCrawler(configConfig, logger, mq, crawlerService)
	application := newApplication(logger, crawlerCrawler)
	return application, nil
}
