app_id: sync-ethereum
release: false

logger:
  level: TRACE
  format: console # json, console

http:
  port: 8080

mq:
  driver: confluentkafka
  confluentkafka_option:
    brokers: 
      - localhost:9092
    consumer_group: "sync-ethereum"
    group_id: "sync-ethereum"
    

database:
  driver: mysql
  host: localhost
  port: 3306
  user: test
  password: test
  database: local
  max_open_conn: 50

eth_client:
  url: https://data-seed-prebsc-2-s3.binance.org:8545/
  dial_timeout: 10s

scheduler:
  unstable_num: 20
  start_at: 9097684
  batch_limit: 100
  sync:
    interval: 5s

crawler:
  topic: "eth_crawler" 
  pool_size: 100
  timeout: 10s

database_writer:
  topic: "eth_database_writer"
  pool_size: 100
  timeout: 10s
  