// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package scheduler

import (
	"sync-ethereum/internal/config"
	"sync-ethereum/internal/delivery/scheduler"
	"sync-ethereum/internal/repository/gorm"
	"sync-ethereum/internal/service/ethclient_crawler"
	"sync-ethereum/internal/service/storage"
	"sync-ethereum/internal/wireset"
)

// Injectors from wire.go:

func Initialize(configPath string) (Application, error) {
	configConfig, err := config.NewConfig(configPath)
	if err != nil {
		return Application{}, err
	}
	logger, err := wireset.InitLogger(configConfig)
	if err != nil {
		return Application{}, err
	}
	db, err := wireset.InitDatabase(configConfig, logger)
	if err != nil {
		return Application{}, err
	}
	mq, err := wireset.InitMQ(configConfig, logger)
	if err != nil {
		return Application{}, err
	}
	crawlerService := ethclient_crawler.NewEthClientCrawlerService(configConfig)
	storageRepository := gorm.NewStorageRepository(db)
	storageService := storage.NewStorageService(storageRepository)
	schedulerScheduler := scheduler.NewScheduler(configConfig, logger, db, mq, crawlerService, storageService)
	application := newApplication(logger, schedulerScheduler)
	return application, nil
}
